openapi: '3.0.3'
info:
  version: 1.0.0
  title: jwt-auth-service
  description: An authentication service following JWT authentication strategy
servers:
  - url: 'http://localhost:8000/api'
tags:
  - name: Health
    description: Call to monitor the health of the service
security:
  - BearerAuth: []

paths:
  /health:
    $ref: health.yaml
  /login:
    $ref: login.yaml
  /register:
    $ref: register.yaml
  /tokens/refresh:
    $ref: tokensRefresh.yaml
  /tokens/verify:
    $ref: tokensVerify.yaml
  /logout:
    $ref: logout.yaml

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    $ref: schemas.yaml
